export enum DiagnosticSeverity {
  ERROR = 'Error',
  WARNING = 'Warning',
  INFO = 'Info',
}

export enum DiagnosticCode {
  SYNTAX_ERROR = 'SYNTAX_ERROR',
  SEMANTIC_INHERITANCE_MISMATCH = 'SEMANTIC_INHERITANCE_MISMATCH',
  SEMANTIC_REALIZATION_INVALID = 'SEMANTIC_REALIZATION_INVALID',
  SEMANTIC_CYCLE_DETECTED = 'SEMANTIC_CYCLE_DETECTED',
  SEMANTIC_DUPLICATE_MEMBER = 'SEMANTIC_DUPLICATE_MEMBER',
  SEMANTIC_INVALID_PACKAGE_RELATIONSHIP = 'SEMANTIC_INVALID_PACKAGE_RELATIONSHIP',
  SEMANTIC_INVALID_TYPE = 'SEMANTIC_INVALID_TYPE',
  SEMANTIC_IMPLICIT_ENTITY = 'SEMANTIC_IMPLICIT_ENTITY',
  SEMANTIC_INVALID_REFERENCE = 'SEMANTIC_INVALID_REFERENCE',
}

export interface Diagnostic {
  message: string
  code?: DiagnosticCode
  line: number
  column: number
  length?: number
  severity: DiagnosticSeverity
}
